# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_linear_laplace <- function(X, Y, mu, sigma, gamma, alpha, beta, lambda, update_order, prioritized_init, ridge_penalty, max_iter, tol, exact_math) {
    .Call(`_sparsevb_fit_linear_laplace`, X, Y, mu, sigma, gamma, alpha, beta, lambda, update_order, prioritized_init, ridge_penalty, max_iter, tol, exact_math)
}

fit_linear_gaussian <- function(X, Y, mu, sigma, gamma, alpha, beta, lambda, update_order, prioritized_init, ridge_penalty, max_iter, tol, exact_math) {
    .Call(`_sparsevb_fit_linear_gaussian`, X, Y, mu, sigma, gamma, alpha, beta, lambda, update_order, prioritized_init, ridge_penalty, max_iter, tol, exact_math)
}

fit_logistic_laplace <- function(X, Y, mu, sigma, gamma, alpha, beta, lambda, update_order, prioritized_init, ridge_penalty, max_iter, tol) {
    .Call(`_sparsevb_fit_logistic_laplace`, X, Y, mu, sigma, gamma, alpha, beta, lambda, update_order, prioritized_init, ridge_penalty, max_iter, tol)
}

fit_logistic_gaussian <- function(X, Y, mu, sigma, gamma, alpha, beta, lambda, update_order, prioritized_init, ridge_penalty, max_iter, tol) {
    .Call(`_sparsevb_fit_logistic_gaussian`, X, Y, mu, sigma, gamma, alpha, beta, lambda, update_order, prioritized_init, ridge_penalty, max_iter, tol)
}

