// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEnsmallen.h>
#include <Rcpp.h>

using namespace Rcpp;

// fit_linear_laplace
Rcpp::List fit_linear_laplace(const arma::mat& X, const arma::vec& Y, arma::vec& mu, arma::vec& sigma, arma::vec& gamma, const double& alpha, const double& beta, const double& lambda, arma::uvec& update_order, const bool& prioritized_init, const double& ridge_penalty, const size_t& max_iter, const double& tol, const bool& exact_math);
RcppExport SEXP _sparsevb_fit_linear_laplace(SEXP XSEXP, SEXP YSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP gammaSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP lambdaSEXP, SEXP update_orderSEXP, SEXP prioritized_initSEXP, SEXP ridge_penaltySEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP exact_mathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const double& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type update_order(update_orderSEXP);
    Rcpp::traits::input_parameter< const bool& >::type prioritized_init(prioritized_initSEXP);
    Rcpp::traits::input_parameter< const double& >::type ridge_penalty(ridge_penaltySEXP);
    Rcpp::traits::input_parameter< const size_t& >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const bool& >::type exact_math(exact_mathSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_linear_laplace(X, Y, mu, sigma, gamma, alpha, beta, lambda, update_order, prioritized_init, ridge_penalty, max_iter, tol, exact_math));
    return rcpp_result_gen;
END_RCPP
}
// fit_linear_gaussian
Rcpp::List fit_linear_gaussian(const arma::mat& X, const arma::vec& Y, arma::vec& mu, arma::vec& sigma, arma::vec& gamma, const double& alpha, const double& beta, const double& lambda, arma::uvec& update_order, const bool& prioritized_init, const double& ridge_penalty, const size_t& max_iter, const double& tol, const bool& exact_math);
RcppExport SEXP _sparsevb_fit_linear_gaussian(SEXP XSEXP, SEXP YSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP gammaSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP lambdaSEXP, SEXP update_orderSEXP, SEXP prioritized_initSEXP, SEXP ridge_penaltySEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP exact_mathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const double& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type update_order(update_orderSEXP);
    Rcpp::traits::input_parameter< const bool& >::type prioritized_init(prioritized_initSEXP);
    Rcpp::traits::input_parameter< const double& >::type ridge_penalty(ridge_penaltySEXP);
    Rcpp::traits::input_parameter< const size_t& >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const bool& >::type exact_math(exact_mathSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_linear_gaussian(X, Y, mu, sigma, gamma, alpha, beta, lambda, update_order, prioritized_init, ridge_penalty, max_iter, tol, exact_math));
    return rcpp_result_gen;
END_RCPP
}
// fit_logistic_laplace
Rcpp::List fit_logistic_laplace(const arma::mat& X, const arma::vec& Y, arma::vec& mu, arma::vec& sigma, arma::vec& gamma, const double& alpha, const double& beta, const double& lambda, arma::uvec& update_order, const bool& prioritized_init, const double& ridge_penalty, const size_t& max_iter, const double& tol);
RcppExport SEXP _sparsevb_fit_logistic_laplace(SEXP XSEXP, SEXP YSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP gammaSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP lambdaSEXP, SEXP update_orderSEXP, SEXP prioritized_initSEXP, SEXP ridge_penaltySEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const double& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type update_order(update_orderSEXP);
    Rcpp::traits::input_parameter< const bool& >::type prioritized_init(prioritized_initSEXP);
    Rcpp::traits::input_parameter< const double& >::type ridge_penalty(ridge_penaltySEXP);
    Rcpp::traits::input_parameter< const size_t& >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_logistic_laplace(X, Y, mu, sigma, gamma, alpha, beta, lambda, update_order, prioritized_init, ridge_penalty, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// fit_logistic_gaussian
Rcpp::List fit_logistic_gaussian(const arma::mat& X, const arma::vec& Y, arma::vec& mu, arma::vec& sigma, arma::vec& gamma, const double& alpha, const double& beta, const double& lambda, arma::uvec& update_order, const bool& prioritized_init, const double& ridge_penalty, const size_t& max_iter, const double& tol);
RcppExport SEXP _sparsevb_fit_logistic_gaussian(SEXP XSEXP, SEXP YSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP gammaSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP lambdaSEXP, SEXP update_orderSEXP, SEXP prioritized_initSEXP, SEXP ridge_penaltySEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const double& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type update_order(update_orderSEXP);
    Rcpp::traits::input_parameter< const bool& >::type prioritized_init(prioritized_initSEXP);
    Rcpp::traits::input_parameter< const double& >::type ridge_penalty(ridge_penaltySEXP);
    Rcpp::traits::input_parameter< const size_t& >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_logistic_gaussian(X, Y, mu, sigma, gamma, alpha, beta, lambda, update_order, prioritized_init, ridge_penalty, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sparsevb_fit_linear_laplace", (DL_FUNC) &_sparsevb_fit_linear_laplace, 14},
    {"_sparsevb_fit_linear_gaussian", (DL_FUNC) &_sparsevb_fit_linear_gaussian, 14},
    {"_sparsevb_fit_logistic_laplace", (DL_FUNC) &_sparsevb_fit_logistic_laplace, 13},
    {"_sparsevb_fit_logistic_gaussian", (DL_FUNC) &_sparsevb_fit_logistic_gaussian, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_sparsevb(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
